HTTP_SERVER_STRING_MACRO(HEAD_BEGIN,"head_begin","<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"><meta name=\"viewport\" content=\"width=512\"><meta name=\"robots\" content=\"noindex, nofollow\"><title>")
HTTP_SERVER_STRING_MACRO(HEAD_END,"head_end","</title>\r\n<link rel=\"stylesheet\" href=\"/main.css\" type=\"text/css\">\r\n<link rel=\"shortcut icon\" href=\"/favicon.ico\" type=\"image/x-icon\">\r\n</head>\r\n<body>")
HTTP_SERVER_STRING_MACRO(RESULT_TR,"result_tr","<tr class=\"")
HTTP_SERVER_STRING_MACRO(RESULT_TR2,"result_tr2","\">")
HTTP_SERVER_STRING_MACRO(RESULT_TD,"result_td","<td class=\"")
HTTP_SERVER_STRING_MACRO(RESULT_TD2,"result_td2","\">")
HTTP_SERVER_STRING_MACRO(RESULT_NOBR,"result_nobr","<span class=\"nobr\"><nobr>")
HTTP_SERVER_STRING_MACRO(RESULT_A,"result_a","<a href=\"")
HTTP_SERVER_STRING_MACRO(RESULT_A2,"result_a2","\">")
HTTP_SERVER_STRING_MACRO(RESULT_ICON,"result_icon","<img class=\"icon\" src=\"/")
HTTP_SERVER_STRING_MACRO(RESULT_ICON2,"result_icon2","\" alt=\"\">")
HTTP_SERVER_STRING_MACRO(RESULT_A_END,"result_a_end","</a>")
HTTP_SERVER_STRING_MACRO(RESULT_TD_END,"result_td_end","</td>")
HTTP_SERVER_STRING_MACRO(RESULT_NOBR_END,"result_nobr_end","</nobr></span>")
HTTP_SERVER_STRING_MACRO(RESULT_TR_END,"result_tr_end","</tr>\r\n")
HTTP_SERVER_STRING_MACRO(BODY_END,"body_end","</body>")
HTTP_SERVER_STRING_MACRO(ERROR1,"error1","<html><meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"><meta name=\"viewport\" content=\"width=512\"><head><title>")
HTTP_SERVER_STRING_MACRO(ERROR2,"error2","</title></head><body>")
HTTP_SERVER_STRING_MACRO(ERROR3,"error3","</body></html>")
HTTP_SERVER_STRING_MACRO(PATH_INDEX_OF,"path_index_of","<tr><td colspan=\"3\"><p class=\"indexof\">")
HTTP_SERVER_STRING_MACRO(PATH_INDEX_OF2,"path_index_of2","</p></td></tr>\r\n")
HTTP_SERVER_STRING_MACRO(PATH_UPDIR,"path_updir","<tr><td class=\"updir\" colspan=\"3\"><a href=\"/")
HTTP_SERVER_STRING_MACRO(PATH_UPDIR2,"path_updir2","\"><img class=\"icon\" src=\"/updir.gif\" alt=\"\">")
HTTP_SERVER_STRING_MACRO(PATH_UPDIR3,"path_updir3","</a></td></tr>\r\n")
HTTP_SERVER_STRING_MACRO(QUERY_NUMRESULTS,"query_numresults","<tr><td colspan=\"4\"><p class=\"numresults\">")
HTTP_SERVER_STRING_MACRO(QUERY_NUMRESULTS2,"query_numresults2","</p></td></tr>\r\n")
HTTP_SERVER_STRING_MACRO(QUERY_PAGE,"query_page","<center><br><br>")
HTTP_SERVER_STRING_MACRO(QUERY_PREV,"query_prev","<span class=\"prevnext\"><a href=\"/")
HTTP_SERVER_STRING_MACRO(QUERY_PREV2,"query_prev2","\">")
HTTP_SERVER_STRING_MACRO(QUERY_PREV3,"query_prev3","</a></span>")
HTTP_SERVER_STRING_MACRO(QUERY_NAV,"query_nav","<span class=\"nav\">...</span>")
HTTP_SERVER_STRING_MACRO(QUERY_CUR,"query_cur","<span class=\"nav\"><b>")
HTTP_SERVER_STRING_MACRO(QUERY_CUR2,"query_cur2","</b></span>")
HTTP_SERVER_STRING_MACRO(QUERY_NUM,"query_num","<span class=\"nav\"><a class=num href=\"/")
HTTP_SERVER_STRING_MACRO(QUERY_NUM2,"query_num2","\">")
HTTP_SERVER_STRING_MACRO(QUERY_NUM3,"query_num3","</a></span>")
HTTP_SERVER_STRING_MACRO(QUERY_NEXT,"query_next","<span class=\"prevnext\"><a href=\"/")
HTTP_SERVER_STRING_MACRO(QUERY_NEXT2,"query_next2","\">")
HTTP_SERVER_STRING_MACRO(QUERY_NEXT3,"query_next3","</a></span>")
HTTP_SERVER_STRING_MACRO(QUERY_PAGE_END,"query_page_end","</center>")
HTTP_SERVER_STRING_MACRO(TB_CENTER,"tb_center","<center>\r\n")
HTTP_SERVER_STRING_MACRO(TB_LOGO,"tb_logo","<br>\r\n<br>\r\n")
HTTP_SERVER_STRING_MACRO(TB_LOGO2,"tb_logo2","<a href=\"/\"><img class=\"logo\" src=\"/Everything.gif\" alt=\"")
HTTP_SERVER_STRING_MACRO(TB_LOGO3,"tb_logo3","\"></a>\r\n")
HTTP_SERVER_STRING_MACRO(TB_FORM,"tb_form","<br>\r\n<br>\r\n")
HTTP_SERVER_STRING_MACRO(TB_FORM2,"tb_form2","<form id=\"searchform\" action=\"/\" method=\"get\"><input class=\"searchbox\" style=\"width:480px\" id=\"search\" name=\"search\" type=\"text\" onfocus=\"this.select()\" title=\"")
HTTP_SERVER_STRING_MACRO(TB_FORM3,"tb_form3","\" value=\"")
HTTP_SERVER_STRING_MACRO(TB_FORM4,"tb_form4","\" autofocus>")
HTTP_SERVER_STRING_MACRO(TB_FORM5,"tb_form5","<input type=\"hidden\" name=\"sort\" value=\"")
HTTP_SERVER_STRING_MACRO(TB_FORM6,"tb_form6","\" /><input type=\"hidden\" name=\"ascending\" value=\"")
HTTP_SERVER_STRING_MACRO(TB_FORM7,"tb_form7","\" />")
HTTP_SERVER_STRING_MACRO(TB_FORM8,"tb_form8","</form>\r\n")
HTTP_SERVER_STRING_MACRO(TB_TABLE,"tb_table","<table cellspacing=\"0\" width=\"480px\">\r\n")
HTTP_SERVER_STRING_MACRO(TH_TD,"th_td","<td class=\"")
HTTP_SERVER_STRING_MACRO(TH_TD2,"th_td2","\">")
HTTP_SERVER_STRING_MACRO(TH_TD3,"th_td3","<a href=\"/")
HTTP_SERVER_STRING_MACRO(TH_TD4,"th_td4","\">")
HTTP_SERVER_STRING_MACRO(TH_NOBR,"th_nobr","<span class=\"nobr\"><nobr>")
HTTP_SERVER_STRING_MACRO(TH_UPDOWN,"th_updown","<img class=\"updown\" src=\"/")
HTTP_SERVER_STRING_MACRO(TH_UPDOWN2,"th_updown2","\" alt=\"\">")
HTTP_SERVER_STRING_MACRO(TH_NOBR_END,"th_nobr_end","</nobr></span>")
HTTP_SERVER_STRING_MACRO(TH_A_END,"th_a_end","</a>")
HTTP_SERVER_STRING_MACRO(TH_TD_END,"th_td_end","</td>")
HTTP_SERVER_STRING_MACRO(THS_TR,"ths_tr","<tr>")
HTTP_SERVER_STRING_MACRO(THS_LINE,"ths_line","<tr><td colspan=\"")
HTTP_SERVER_STRING_MACRO(THS_LINE2,"ths_line2","\" class=\"lineshadow\" height=\"1\"></td></tr>\r\n")
HTTP_SERVER_STRING_MACRO(THS_TR_END,"ths_tr_end","</tr>\r\n")
HTTP_SERVER_STRING_MACRO(TE_END,"te_end","</table>\r\n</center>\r\n")

