#define PLUGINYEAR		2025
#define PLUGINMAJOR 	1
#define PLUGINMINOR 	0
#define PLUGINREVISION	5
#define PLUGINBUILD		6

#define _PLUGINVERSIONSTR2(x)	#x
#define _PLUGINVERSIONSTR(x)	_PLUGINVERSIONSTR2(x)
#define PLUGINVERSION			_PLUGINVERSIONSTR(PLUGINMAJOR.PLUGINMINOR.PLUGINREVISION.PLUGINBUILD)
